from witwin.core import Box, Cone, Cylinder, Ellipsoid, HollowBox, Mesh, Prism, Pyramid, Sphere, Structure, Torus
from witwin.core.geometry import ComplexPolySlab, PolySlab
from .media import DebyePole, DiagonalTensor3, DrudePole, LorentzPole, Material, Tensor3x3
from .monitors import (
    ClosedSurfaceMonitor,
    DiffractionMonitor,
    DipoleEmissionMonitor,
    FieldTimeMonitor,
    FinitePlaneMonitor,
    FluxMonitor,
    FluxTimeMonitor,
    MediumMonitor,
    ModeMonitor,
    PermittivityMonitor,
    PlaneMonitor,
    PointMonitor,
)
from .ports import ModePort
from . import postprocess
from .result import Result
from .scene import (
    BoundaryKind,
    BoundarySpec,
    Domain,
    GridSpec,
    LayerRefinementSpec,
    MaterialRegion,
    MeshOverrideStructure,
    Scene,
    SceneModule,
)
from .sources import (
    AstigmaticGaussianBeam,
    CurrentDataset,
    CustomCurrentSource,
    CustomFieldSource,
    CustomSourceTime,
    CW,
    FieldDataset,
    GaussianBeam,
    GaussianPulse,
    ModeSource,
    PlaneWave,
    PointDipole,
    RickerWavelet,
    TFSF,
    UniformCurrentSource,
)
from .simulation import (
    AbsorberKind,
    FDFDConfig,
    FDTDConfig,
    GMRES,
    Simulation,
    SimulationMethod,
    SpectralSampler,
    SpectralWindowKind,
    TimeConfig,
    run,
)

__all__ = [
    "AstigmaticGaussianBeam",
    "BoundarySpec",
    "BoundaryKind",
    "Box",
    "ClosedSurfaceMonitor",
    "ComplexPolySlab",
    "DiffractionMonitor",
    "Cone",
    "CurrentDataset",
    "CustomCurrentSource",
    "CustomFieldSource",
    "CW",
    "CustomSourceTime",
    "Cylinder",
    "DebyePole",
    "DipoleEmissionMonitor",
    "Domain",
    "DrudePole",
    "Ellipsoid",
    "FieldDataset",
    "FieldTimeMonitor",
    "FluxMonitor",
    "FluxTimeMonitor",
    "FDFDConfig",
    "FDTDConfig",
    "FinitePlaneMonitor",
    "GaussianBeam",
    "GaussianPulse",
    "GMRES",
    "GridSpec",
    "HollowBox",
    "LayerRefinementSpec",
    "LorentzPole",
    "Material",
    "MaterialRegion",
    "MediumMonitor",
    "Mesh",
    "MeshOverrideStructure",
    "ModeMonitor",
    "ModePort",
    "ModeSource",
    "PermittivityMonitor",
    "PlaneMonitor",
    "PlaneWave",
    "PointDipole",
    "PointMonitor",
    "PolySlab",
    "postprocess",
    "Prism",
    "Pyramid",
    "Result",
    "RickerWavelet",
    "Scene",
    "SceneModule",
    "Simulation",
    "SimulationMethod",
    "SpectralSampler",
    "SpectralWindowKind",
    "Sphere",
    "Structure",
    "Tensor3x3",
    "TimeConfig",
    "TFSF",
    "Torus",
    "UniformCurrentSource",
    "DiagonalTensor3",
    "AbsorberKind",
    "run",
]


def __getattr__(name):
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
