from witwin.core import Box, Cone, Cylinder, Ellipsoid, HollowBox, Mesh, Prism, Pyramid, Sphere, Structure, Torus
from .geometry import ComplexPolySlab, PolySlab
from .media import (
    CustomDebyePole,
    CustomDrudePole,
    CustomLorentzPole,
    DebyePole,
    DiagonalTensor3,
    DrudePole,
    Graphene,
    LorentzPole,
    Material,
    Medium2D,
    ModulationSpec,
    NonlinearSusceptibility,
    PerturbationMedium,
    Tensor3x3,
    TwoPhotonAbsorption,
)
from .monitors import (
    ClosedSurfaceMonitor,
    DiffractionMonitor,
    DipoleEmissionMonitor,
    FieldTimeMonitor,
    FinitePlaneMonitor,
    FluxMonitor,
    FluxTimeMonitor,
    MediumMonitor,
    ModeMonitor,
    PermittivityMonitor,
    PlaneMonitor,
    PointMonitor,
)
from .ports import ModePort
from . import postprocess
from .result import Result
from .scene import (
    BoundaryKind,
    BoundarySpec,
    Domain,
    GridSpec,
    LayerRefinementSpec,
    MaterialRegion,
    MeshOverrideStructure,
    Scene,
    SceneModule,
    SubpixelSpec,
)
from .sources import (
    AstigmaticGaussianBeam,
    CurrentDataset,
    CustomCurrentSource,
    CustomFieldSource,
    CustomSourceTime,
    CW,
    FieldDataset,
    GaussianBeam,
    GaussianPulse,
    ModeSource,
    PlaneWave,
    PointDipole,
    RickerWavelet,
    TFSF,
    UniformCurrentSource,
)
from .simulation import (
    AbsorberKind,
    FDFDConfig,
    FDTDConfig,
    GMRES,
    Simulation,
    SimulationMethod,
    SpectralSampler,
    SpectralWindowKind,
    TimeConfig,
    run,
)

__all__ = [
    "AstigmaticGaussianBeam",
    "BoundarySpec",
    "BoundaryKind",
    "Box",
    "ClosedSurfaceMonitor",
    "ComplexPolySlab",
    "DiffractionMonitor",
    "Cone",
    "CurrentDataset",
    "CustomCurrentSource",
    "CustomFieldSource",
    "CW",
    "CustomDebyePole",
    "CustomDrudePole",
    "CustomLorentzPole",
    "CustomSourceTime",
    "Cylinder",
    "DebyePole",
    "DipoleEmissionMonitor",
    "Domain",
    "DrudePole",
    "Ellipsoid",
    "FieldDataset",
    "FieldTimeMonitor",
    "FluxMonitor",
    "FluxTimeMonitor",
    "FDFDConfig",
    "FDTDConfig",
    "FinitePlaneMonitor",
    "GaussianBeam",
    "GaussianPulse",
    "GMRES",
    "Graphene",
    "GridSpec",
    "HollowBox",
    "LayerRefinementSpec",
    "LorentzPole",
    "Material",
    "MaterialRegion",
    "Medium2D",
    "MediumMonitor",
    "Mesh",
    "MeshOverrideStructure",
    "ModeMonitor",
    "ModePort",
    "ModeSource",
    "ModulationSpec",
    "NonlinearSusceptibility",
    "PermittivityMonitor",
    "PerturbationMedium",
    "PlaneMonitor",
    "PlaneWave",
    "PointDipole",
    "PointMonitor",
    "PolySlab",
    "postprocess",
    "Prism",
    "Pyramid",
    "Result",
    "RickerWavelet",
    "Scene",
    "SceneModule",
    "Simulation",
    "SimulationMethod",
    "SpectralSampler",
    "SpectralWindowKind",
    "Sphere",
    "Structure",
    "SubpixelSpec",
    "Tensor3x3",
    "TimeConfig",
    "TFSF",
    "Torus",
    "TwoPhotonAbsorption",
    "UniformCurrentSource",
    "DiagonalTensor3",
    "AbsorberKind",
    "run",
]


def __getattr__(name):
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
