from witwin.core import Box, Cone, Cylinder, Ellipsoid, HollowBox, Mesh, Prism, Pyramid, Sphere, Structure, Torus
from .media import DebyePole, DiagonalTensor3, DrudePole, LorentzPole, Material, Tensor3x3
from .monitors import (
    ClosedSurfaceMonitor,
    FieldTimeMonitor,
    FinitePlaneMonitor,
    FluxMonitor,
    FluxTimeMonitor,
    MediumMonitor,
    ModeMonitor,
    PermittivityMonitor,
    PlaneMonitor,
    PointMonitor,
)
from .ports import ModePort
from . import postprocess
from .result import Result
from .scene import BoundaryKind, BoundarySpec, Domain, GridSpec, MaterialRegion, Scene, SceneModule
from .sources import (
    AstigmaticGaussianBeam,
    CustomSourceTime,
    CW,
    GaussianBeam,
    GaussianPulse,
    ModeSource,
    PlaneWave,
    PointDipole,
    RickerWavelet,
    TFSF,
)
from .simulation import (
    AbsorberKind,
    FDFDConfig,
    FDTDConfig,
    GMRES,
    Simulation,
    SimulationMethod,
    SpectralSampler,
    SpectralWindowKind,
    TimeConfig,
    run,
)

__all__ = [
    "AstigmaticGaussianBeam",
    "BoundarySpec",
    "BoundaryKind",
    "Box",
    "ClosedSurfaceMonitor",
    "Cone",
    "CW",
    "CustomSourceTime",
    "Cylinder",
    "DebyePole",
    "Domain",
    "DrudePole",
    "Ellipsoid",
    "FieldTimeMonitor",
    "FluxMonitor",
    "FluxTimeMonitor",
    "FDFDConfig",
    "FDTDConfig",
    "FinitePlaneMonitor",
    "GaussianBeam",
    "GaussianPulse",
    "GMRES",
    "GridSpec",
    "HollowBox",
    "LorentzPole",
    "Material",
    "MaterialRegion",
    "MediumMonitor",
    "Mesh",
    "ModeMonitor",
    "ModePort",
    "ModeSource",
    "PermittivityMonitor",
    "PlaneMonitor",
    "PlaneWave",
    "PointDipole",
    "PointMonitor",
    "postprocess",
    "Prism",
    "Pyramid",
    "Result",
    "RickerWavelet",
    "Scene",
    "SceneModule",
    "Simulation",
    "SimulationMethod",
    "SpectralSampler",
    "SpectralWindowKind",
    "Sphere",
    "Structure",
    "Tensor3x3",
    "TimeConfig",
    "TFSF",
    "Torus",
    "DiagonalTensor3",
    "AbsorberKind",
    "run",
]


def __getattr__(name):
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
