"""Combination: several distinct space-time modulation frequencies in one Scene.

The single-modulation-frequency-per-scene cap is lifted. The runtime no longer
carries one scalar modulation frequency; instead every Yee edge holds its own
angular frequency (the ``mod_omega`` field), and the modulated E-update kernels
evaluate the per-cell phase ``cos/sin(omega(x) * t)`` from it. This lets disjoint
structures modulate at independent frequencies in a single run.

The physics check is a frequency-domain fingerprint. A carrier CW plane wave
crosses two disjoint slabs in series, slab A driven at ``Omega_A`` and slab B at
``Omega_B``. A correct per-cell implementation must produce first-order sidebands
at ``omega_c +/- Omega_A`` (generated by slab A) *and* ``omega_c +/- Omega_B``
(generated by slab B). A buggy single-global-frequency implementation would drive
both slabs at one frequency and one of the two sideband pairs would vanish.

Each slab's contribution is pinned quantitatively by a single-slab cross-check:
running with only slab B modulated (slab A static) reproduces the ``Omega_B``
sideband and shows no ``Omega_A`` sideband, and vice versa. There are no magic
constants: the sideband bins are the analytic ``omega_c +/- Omega`` mixing
products, and every threshold is expressed relative to the measured carrier or
the matching single-slab run.
"""

from __future__ import annotations

import numpy as np
import pytest
import torch

import witwin.maxwell as mw
from witwin.core import Box


_CARRIER = 1.5e9
_OMEGA_A = 2.0e8
_OMEGA_B = 3.0e8


def _to_numpy(value):
    if isinstance(value, torch.Tensor):
        return value.detach().cpu().numpy()
    return np.asarray(value)


def _build_two_slab_scene(*, mod_a, mod_b, amplitude=80.0):
    """Two disjoint eps_r=4 slabs in series along +x, each optionally modulated.

    ``mod_a`` / ``mod_b`` are ``ModulationSpec`` or ``None`` (static slab). The
    slabs never overlap, so each modulated cell has a single, unambiguous
    frequency; the probe sits downstream of both slabs.
    """
    material_a = mw.Material(eps_r=4.0, modulation=mod_a) if mod_a is not None else mw.Material(eps_r=4.0)
    material_b = mw.Material(eps_r=4.0, modulation=mod_b) if mod_b is not None else mw.Material(eps_r=4.0)
    scene = mw.Scene(
        domain=mw.Domain(bounds=((-0.6, 0.6), (-0.16, 0.16), (-0.16, 0.16))),
        grid=mw.GridSpec.uniform(0.02),
        boundary=mw.BoundarySpec.pml(num_layers=6, strength=1.0),
        device="cuda",
        sources=[
            mw.PlaneWave(
                direction=(1.0, 0.0, 0.0),
                polarization=(0.0, 0.0, 1.0),
                source_time=mw.CW(frequency=_CARRIER, amplitude=amplitude),
                name="pw",
            )
        ],
        structures=[
            mw.Structure(
                geometry=Box(position=(-0.15, 0.0, 0.0), size=(0.16, 0.64, 0.64)),
                material=material_a,
            ),
            mw.Structure(
                geometry=Box(position=(0.15, 0.0, 0.0), size=(0.16, 0.64, 0.64)),
                material=material_b,
            ),
        ],
    )
    scene.add_monitor(
        mw.FieldTimeMonitor("probe", components=("Ez",), position=(0.42, 0.0, 0.0), interval=1)
    )
    return scene


def _run(scene, *, time_steps):
    result = mw.Simulation.fdtd(
        scene,
        frequencies=[_CARRIER],
        run_time=mw.TimeConfig(time_steps=time_steps),
        full_field_dft=False,
    ).run()
    trace = _to_numpy(result.monitor("probe")["field"]).astype(np.float64)
    dt = float(result.solver.dt)
    del result
    torch.cuda.empty_cache()
    return trace, dt


def _spectrum(trace, dt):
    """Windowed-FFT power spectrum over the steady-state tail."""
    tail = trace[len(trace) // 4 :]
    window = np.hanning(tail.size)
    spectrum = np.fft.rfft(tail * window)
    freqs = np.fft.rfftfreq(tail.size, d=dt)
    return freqs, np.abs(spectrum) ** 2


def _peak_power(freqs, power, target):
    index = int(np.argmin(np.abs(freqs - target)))
    low = max(index - 2, 0)
    high = min(index + 3, power.size)
    return float(power[low:high].max())


def _sideband_powers(trace, dt):
    """(carrier, A-lower, A-upper, B-lower, B-upper) first-order sideband powers."""
    freqs, power = _spectrum(trace, dt)
    return (
        _peak_power(freqs, power, _CARRIER),
        _peak_power(freqs, power, _CARRIER - _OMEGA_A),
        _peak_power(freqs, power, _CARRIER + _OMEGA_A),
        _peak_power(freqs, power, _CARRIER - _OMEGA_B),
        _peak_power(freqs, power, _CARRIER + _OMEGA_B),
    )


@pytest.mark.skipif(not torch.cuda.is_available(), reason="needs CUDA for FDTD")
def test_two_frequency_modulation_generates_both_sideband_pairs():
    time_steps = 4096
    spec_a = mw.ModulationSpec(frequency=_OMEGA_A, amplitude=0.25)
    spec_b = mw.ModulationSpec(frequency=_OMEGA_B, amplitude=0.25)

    both_trace, dt = _run(_build_two_slab_scene(mod_a=spec_a, mod_b=spec_b), time_steps=time_steps)
    a_only_trace, dt_a = _run(_build_two_slab_scene(mod_a=spec_a, mod_b=None), time_steps=time_steps)
    b_only_trace, dt_b = _run(_build_two_slab_scene(mod_a=None, mod_b=spec_b), time_steps=time_steps)
    assert dt == dt_a == dt_b

    carrier, a_lo, a_hi, b_lo, b_hi = _sideband_powers(both_trace, dt)
    _, a_lo_ref, a_hi_ref, a_b_lo, a_b_hi = _sideband_powers(a_only_trace, dt)
    _, b_a_lo, b_a_hi, b_lo_ref, b_hi_ref = _sideband_powers(b_only_trace, dt)

    assert carrier > 0.0

    # (1) The two-frequency run must show BOTH sideband pairs. A single-global-
    #     frequency implementation would drive both slabs at one Omega and one of
    #     these pairs would be absent.
    assert a_lo > 1.0e-3 * carrier
    assert a_hi > 1.0e-3 * carrier
    assert b_lo > 1.0e-3 * carrier
    assert b_hi > 1.0e-3 * carrier

    # (2) Each sideband is pinned to its own slab: removing a slab's modulation
    #     removes exactly that slab's sideband pair. The A-only run has no Omega_B
    #     sideband, and the B-only run has no Omega_A sideband (both far below the
    #     level they reach when their slab is actually modulated).
    assert a_b_lo < 1.0e-2 * b_lo
    assert a_b_hi < 1.0e-2 * b_hi
    assert b_a_lo < 1.0e-2 * a_lo
    assert b_a_hi < 1.0e-2 * a_hi

    # (3) Each slab uses ITS OWN frequency: the two-frequency Omega_A sideband
    #     matches the A-only run and the Omega_B sideband matches the B-only run,
    #     within the modest depletion from the second slab also drawing carrier
    #     power. A wrong per-cell frequency would collapse one of these ratios.
    for measured, reference in ((a_lo, a_lo_ref), (a_hi, a_hi_ref), (b_lo, b_lo_ref), (b_hi, b_hi_ref)):
        assert 0.2 < measured / reference < 5.0


@pytest.mark.skipif(not torch.cuda.is_available(), reason="needs CUDA for FDTD")
def test_two_frequency_modulation_runtime_omega_field_is_bimodal():
    # The prepared solver carries a per-edge angular-frequency field whose only
    # nonzero values are the two structure frequencies, confirming the runtime is
    # genuinely multi-frequency rather than collapsing to a single scalar.
    spec_a = mw.ModulationSpec(frequency=_OMEGA_A, amplitude=0.25)
    spec_b = mw.ModulationSpec(frequency=_OMEGA_B, amplitude=0.25)
    scene = _build_two_slab_scene(mod_a=spec_a, mod_b=spec_b)
    solver = mw.Simulation.fdtd(
        scene,
        frequencies=[_CARRIER],
        run_time=mw.TimeConfig(time_steps=8),
        full_field_dft=False,
    ).prepare().solver

    assert solver.modulation_enabled
    omega = solver.mod_omega_Ez
    present = torch.unique(omega[omega != 0]).detach().cpu().numpy()
    present = np.sort(present)
    assert present.size == 2
    assert present[0] == pytest.approx(2.0 * np.pi * _OMEGA_A, rel=1e-4)
    assert present[1] == pytest.approx(2.0 * np.pi * _OMEGA_B, rel=1e-4)
